version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - event-network

  # gateway-server:
  #   build:
  #     context: ./gateway-server
  #     dockerfile: Dockerfile.dev
  #   container_name: gateway-server
  #   restart: no
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./gateway-server:/var/app
  #     - /var/app/node_modules
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - event-network

  # auth-server:
  #   build:
  #     context: ./auth-server
  #     dockerfile: Dockerfile.dev
  #   container_name: auth-server
  #   restart: no
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./auth-server:/var/app
  #     - /var/app/node_modules
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - event-network

  # campaign-server:
  #   build:
  #     context: ./campaign-server
  #     dockerfile: Dockerfile.dev
  #   container_name: campaign-server
  #   restart: no
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #     - ./campaign-server:/var/app
  #     - /var/app/node_modules
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - event-network

networks:
  event-network:
    driver: bridge

volumes:
  mongodb_data:
