version: "3.8"

services:
  # environment:
  #   NODE_ENV=${NODE_ENV}
  #   MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017
  #   JWT_SECRET=${JWT_SECRET}
  #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
  #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always

    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - event-network

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    restart: no
    ports:
      - "${GATEWAY_PORT}:3000"
    depends_on:
      - mongodb
    networks:
      - event-network

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    restart: no
    ports:
      - "${AUTH_PORT}:3001"
    depends_on:
      - mongodb
    networks:
      - event-network

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    container_name: event-server
    restart: no
    ports:
      - "${EVENT_PORT}:3002"
    depends_on:
      - mongodb
    networks:
      - event-network

networks:
  event-network:
    driver: bridge

volumes:
  mongodb_data:
